//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeInvestigationSystemWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddCase
    {
        public AddCase()
        {
            this.AddEvidences = new HashSet<AddEvidence>();
            this.AddResults = new HashSet<AddResult>();
            this.AddSuspects = new HashSet<AddSuspect>();
            this.AddOfficerToCases = new HashSet<AddOfficerToCase>();
            this.AddCaseHistories = new HashSet<AddCaseHistory>();
        }
    
        public int Id { get; set; }
        public string CaseName { get; set; }
        public Nullable<int> OfficerId { get; set; }
        public string Note { get; set; }
        public string CaseId { get; set; }
    
        public virtual AddOfficer AddOfficer { get; set; }
        public virtual ICollection<AddEvidence> AddEvidences { get; set; }
        public virtual ICollection<AddResult> AddResults { get; set; }
        public virtual ICollection<AddSuspect> AddSuspects { get; set; }
        public virtual ICollection<AddOfficerToCase> AddOfficerToCases { get; set; }
        public virtual ICollection<AddCaseHistory> AddCaseHistories { get; set; }
    }
}
