//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeInvestigationSystemWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddOfficer
    {
        public AddOfficer()
        {
            this.AddCases = new HashSet<AddCase>();
            this.AddOfficerToCases = new HashSet<AddOfficerToCase>();
        }
    
        public int Id { get; set; }
        public string OfficerId { get; set; }
        public string OfficerName { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public string Mail { get; set; }
        public string Area { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<AddCase> AddCases { get; set; }
        public virtual ICollection<AddOfficerToCase> AddOfficerToCases { get; set; }
    }
}
