//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeInvestigationSystemWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddSuspect
    {
        public AddSuspect()
        {
            this.AddEvidences = new HashSet<AddEvidence>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CaseId { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public string Relation { get; set; }
        public string Note { get; set; }
        public string Image { get; set; }
        public string Dates { get; set; }
    
        public virtual AddCase AddCase { get; set; }
        public virtual ICollection<AddEvidence> AddEvidences { get; set; }
    }
}
