//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeInvestigationSystemWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrimeInvestigationDBEntities : DbContext
    {
        public CrimeInvestigationDBEntities()
            : base("name=CrimeInvestigationDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddCase> AddCases { get; set; }
        public virtual DbSet<AddEvidence> AddEvidences { get; set; }
        public virtual DbSet<AddOfficer> AddOfficers { get; set; }
        public virtual DbSet<AddResult> AddResults { get; set; }
        public virtual DbSet<AddSuspect> AddSuspects { get; set; }
        public virtual DbSet<AddOfficerToCase> AddOfficerToCases { get; set; }
        public virtual DbSet<OfficerLogin> OfficerLogins { get; set; }
        public virtual DbSet<AddCaseHistory> AddCaseHistories { get; set; }
        public virtual DbSet<AdminLogin> AdminLogins { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
    }
}
