//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeInvestigationSystemWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficerLogin
    {
        public int Id { get; set; }
        public string OfficerId { get; set; }
        public string Password { get; set; }
    
        public virtual OfficerLogin OfficerLogin1 { get; set; }
        public virtual OfficerLogin OfficerLogin2 { get; set; }
    }
}
