//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeInvestigationSystemWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public string CaseName { get; set; }
        public string CaseId { get; set; }
        public string Suspect { get; set; }
        public string Note { get; set; }
        public int Id { get; set; }
    }
}
